# Generated by Django 2.2.5 on 2020-09-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projectapi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Normalized_Work_Effort', models.FloatField()),
                ('Summary_Work_Effort', models.FloatField()),
                ('Normalised_Work_Effort_Level_1', models.FloatField()),
                ('Effort_Unphased', models.FloatField()),
                ('Adjusted_Function_Points', models.FloatField()),
                ('Functional_Size', models.FloatField()),
                ('Added_count', models.FloatField()),
                ('Input_count', models.FloatField()),
                ('Max_Team_Size', models.FloatField()),
                ('Speed_of_Delivery', models.FloatField()),
                ('Development_Type_New_Development', models.FloatField()),
                ('Language_Type_3GL', models.FloatField()),
            ],
        ),
    ]
